[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install --prefix client", "npm install --prefix server"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build --prefix client", "cd server && npx prisma generate && npm run build"]

[deploy]
startCommand = "cd server && npx prisma migrate deploy && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
